context:
  name: winreg
  version: "8.0.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/GiovanniDicanio/WinReg/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 017c08afbc0723ed33333be6204915a4f7b84ef8ad9ab1174e723342b52cb180

build:
  number: 0
  skip: not win
  script: mkdir %LIBRARY_PREFIX%\include\winreg && cp WinReg\WinReg.hpp %LIBRARY_PREFIX%\include\winreg\

tests:
  - package_contents:
      include:
        - winreg/WinReg.hpp

about:
  homepage: https://github.com/GiovanniDicanio/WinReg
  license: MIT
  license_file: LICENSE
  summary: Convenient high-level C++ wrapper around the Windows Registry API

extra:
  recipe-maintainers:
    - wolfv
