context:
  name: winreg
  version: "7.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/GiovanniDicanio/WinReg/archive/refs/tags/v${{ version }}.tar.gz
  sha256: eb238fcc21ea19d79ff0928e2c4e778ea3123ac0bbf48ae13e51c3055bd1f4c7

build:
  number: 0
  skip: not win
  script: mkdir %LIBRARY_PREFIX%\include\winreg && cp WinReg\WinReg.hpp %LIBRARY_PREFIX%\include\winreg\

tests:
  - package_contents:
      include:
        - winreg/WinReg.hpp

about:
  homepage: https://github.com/GiovanniDicanio/WinReg
  license: MIT
  license_file: LICENSE
  summary: Convenient high-level C++ wrapper around the Windows Registry API

extra:
  recipe-maintainers:
    - wolfv
