context:
  name: winreg
  version: "6.5.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/GiovanniDicanio/WinReg/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a0f1e4d53013a068d271e114cb96014ae302e14d4701d872a405bb7f81acf1ab

build:
  number: 0
  skip: not win
  script: mkdir %LIBRARY_PREFIX%\include\winreg && cp WinReg\WinReg.hpp %LIBRARY_PREFIX%\include\winreg\

tests:
  - package_contents:
      include:
        - winreg/WinReg.hpp

about:
  homepage: https://github.com/GiovanniDicanio/WinReg
  license: MIT
  license_file: LICENSE
  summary: Convenient high-level C++ wrapper around the Windows Registry API

extra:
  recipe-maintainers:
    - wolfv
